apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ugu9c90q2-java-springboot 
  janus-idp.io/tekton: ugu9c90q2-java-springboot
  backstage.io/kubernetes-id: ugu9c90q2-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ugu9c90q2-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  